// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqNYfsjUzgPcvmy8oJvT7DM8tjx6pc3zc',
    appId: '1:127827910797:web:be59e14f514937283fc2c4',
    messagingSenderId: '127827910797',
    projectId: 'quiz-app-75be4',
    authDomain: 'quiz-app-75be4.firebaseapp.com',
    storageBucket: 'quiz-app-75be4.firebasestorage.app',
    measurementId: 'G-QG0P9VCJFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjUTYshq-kX1EjPTL1FAbr6hOAWUlFls',
    appId: '1:127827910797:android:4bb01ef5f8672a393fc2c4',
    messagingSenderId: '127827910797',
    projectId: 'quiz-app-75be4',
    storageBucket: 'quiz-app-75be4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqNYfsjUzgPcvmy8oJvT7DM8tjx6pc3zc',
    appId: '1:127827910797:web:002509b0b9da8c9f3fc2c4',
    messagingSenderId: '127827910797',
    projectId: 'quiz-app-75be4',
    authDomain: 'quiz-app-75be4.firebaseapp.com',
    storageBucket: 'quiz-app-75be4.firebasestorage.app',
    measurementId: 'G-ZJN98T3KBH',
  );

}